apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cg
  region: us-east-1
  version: "1.24"
vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: HighlyAvailable
NodeGroups:
  - name: eks-node-group
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true
    volumeSize: 30